name: 'Codegen SDK Action'
description: 'Execute Codegen SDK commands to manipulate and analyze codebases'
author: 'SoftLari'

inputs:
  org_id:
    description: 'Organization ID for Codegen service'
    required: true
  token:
    description: 'API token for Codegen service'
    required: true
  prompt:
    description: 'Prompt to send to Codegen agent'
    required: true
  base_url:
    description: 'Base URL for Codegen API (optional)'
    required: false
    default: 'https://api.codegen.com'
  wait_for_completion:
    description: 'Whether to wait for the task to complete'
    required: false
    default: 'true'
  timeout_seconds:
    description: 'Maximum time to wait for completion in seconds'
    required: false
    default: '300'

outputs:
  task_id:
    description: 'ID of the created task'
    value: ${{ steps.run-agent.outputs.task_id }}
  status:
    description: 'Status of the task'
    value: ${{ steps.run-agent.outputs.status }}
  result:
    description: 'Result of the task (if completed)'
    value: ${{ steps.run-agent.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Run Codegen Agent
      id: run-agent
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/run_agent.sh
        ${{ github.action_path }}/run_agent.sh
      env:
        INPUT_ORG_ID: ${{ inputs.org_id }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PROMPT: ${{ inputs.prompt }}
        INPUT_BASE_URL: ${{ inputs.base_url }}
        INPUT_WAIT_FOR_COMPLETION: ${{ inputs.wait_for_completion }}
        INPUT_TIMEOUT_SECONDS: ${{ inputs.timeout_seconds }}
